  - name: nginx Installation
    hosts: dobbi2
    tasks:
      - name: Installed
        package: 
          name: nginx
          state: present

      - name: started
        service:
          name: nginx
          enabled: yes
          state: started

      - name: SElinux
        ansible.posix.selinux: 
          policy: targeted
          state: disabled

           #- name: copy the HTML file 
           #copy:
           #src: /home/njl/css1
           #dest: /usr/share/nginx/html

      - name: through templates
        ansible.builtin.template:
          src: /home/njl/Ansible/nginx-temp.j2
          dest: /etc/nginx/conf.d/colombo.conf
        notify: hooya

    handlers: 
      - name: hooya 
        service: 
          name: nginx
          state: reloaded
       




