---
  - name: nginx Installation
    hosts: dobbi2
    tasks:
      - name: Installed
        package: 
          name: nginx
          state: present

      - name: started
        service:
          name: nginx
          enabled: yes
          state: started

      - name: SElinux
        ansible.builtin.selinux: 
          policy: targeted
          state: permissive

      - name: firewall configuration
        ansible.builtin.firewalld:
          service: http
          permanent: true
          state: enabled

      - name: restart firewall
        service:
          name: firewalld
          state: restarted
        
      - name: copy conf. file
        copy: 
          src: /home/njl/Ansible/gojo1 
          dest: /var/www/html/siteG
          owner: nginx
          group: nginx
          mode: u=rw,g=r,o=r

           #- name: copy the HTML file 
           #copy:
           #src: /home/njl/css1
           #dest: /usr/share/nginx/html

      - name: through templates
        ansible.builtin.template:
          src: /home/njl/Ansible/nginx-temp.j2
          dest: /etc/nginx/conf.d/colombo.conf
        notify: hooya

    handlers:
      - name: hooya 
        service: 
          name: nginx
          state: restarted

